// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyttIfrCFxwqO8AjDoQfj6z6DXLmmVL8',
    appId: '1:593789696283:web:67b7ed0309d83c62707bbe',
    messagingSenderId: '593789696283',
    projectId: 'taskmaker-98e3f',
    authDomain: 'taskmaker-98e3f.firebaseapp.com',
    storageBucket: 'taskmaker-98e3f.appspot.com',
    measurementId: 'G-EZCC5K0X3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKa9swuS0PftjCvu5S5jT9ApiaP7pjtQ',
    appId: '1:593789696283:android:57d146a087c60439707bbe',
    messagingSenderId: '593789696283',
    projectId: 'taskmaker-98e3f',
    storageBucket: 'taskmaker-98e3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9m252kQ79NqwNwi55WyrVzajXudLfnU',
    appId: '1:593789696283:ios:7dc7ee350fc18454707bbe',
    messagingSenderId: '593789696283',
    projectId: 'taskmaker-98e3f',
    storageBucket: 'taskmaker-98e3f.appspot.com',
    iosBundleId: 'com.example.op1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9m252kQ79NqwNwi55WyrVzajXudLfnU',
    appId: '1:593789696283:ios:0b20b23f33f2c80f707bbe',
    messagingSenderId: '593789696283',
    projectId: 'taskmaker-98e3f',
    storageBucket: 'taskmaker-98e3f.appspot.com',
    iosBundleId: 'com.example.op1.RunnerTests',
  );
}
